rmzamora_calendar_attendee_show:
  pattern:  /show/{id}
  defaults: { _controller: RmzamoraCalendarBundle:Attendee:show }

rmzamora_calendar_attendee_add:
  pattern:  /add/{eventId}
  defaults: { _controller: RmzamoraCalendarBundle:Attendee:add }

rmzamora_calendar_attendee_edit:
  pattern:  /edit/{id}
  defaults: { _controller: RmzamoraCalendarBundle:Attendee:edit }

rmzamora_calendar_attendee_delete:
  pattern: /delete/{id}
  defaults: { _controller: RmzamoraCalendarBundle:Attendee:delete }

rmzamora_calendar_attendee_list:
  pattern:  /{eventId}
  defaults: { _controller: RmzamoraCalendarBundle:Attendee:list }
