rmzamora_calendar_list:
  pattern:  /
  defaults: { _controller: RmzamoraCalendarBundle:Calendar:list }

rmzamora_calendar_listEvents:
  pattern:  /{id}/events
  defaults: { _controller: RmzamoraCalendarBundle:Calendar:listEvents }

rmzamora_calendar_show:
  pattern:  /show/{id}
  defaults: { _controller: RmzamoraCalendarBundle:Calendar:show }

rmzamora_calendar_add:
  pattern:  /add
  defaults: { _controller: RmzamoraCalendarBundle:Calendar:add }

rmzamora_calendar_edit:
  pattern:  /edit/{id}
  defaults: { _controller: RmzamoraCalendarBundle:Calendar:edit }

rmzamora_calendar_delete:
  pattern:  /delete/{id}
  defaults: { _controller: RmzamoraCalendarBundle:Calendar:delete }
