rmzamora_calendar_event_list:
  pattern:  /
  defaults: { _controller: RmzamoraCalendarBundle:Event:list }

rmzamora_calendar_event_show:
  pattern:  /show/{id}
  defaults: { _controller: RmzamoraCalendarBundle:Event:show }

rmzamora_calendar_event_add:
  pattern:  /add/{calendarId}
  defaults: { _controller: RmzamoraCalendarBundle:Event:add }

rmzamora_calendar_event_edit:
  pattern:  /edit/{id}
  defaults: { _controller: RmzamoraCalendarBundle:Event:edit }

rmzamora_calendar_event_delete:
  pattern: /delete/{id}
  defaults: { _controller: RmzamoraCalendarBundle:Event:delete }
